# Build-Stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Solution + Projekt kopieren (für Cache)
COPY *.sln ./
COPY HelfenNeuGedacht.API/*.csproj HelfenNeuGedacht.API/
RUN dotnet restore HelfenNeuGedacht.API/HelfenNeuGedacht.API.csproj

# Restlichen Code kopieren
COPY . .
WORKDIR /src/HelfenNeuGedacht.API

# Build + Publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# Runtime-Stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "HelfenNeuGedacht.API.dll"]
